# Generated by Django 5.1 on 2025-02-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocapacitacion',
            name='organizador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventovisitante',
            name='cat_participante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
