# Generated by Django 5.1 on 2025-02-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_eventocapacitacion_organizador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventovisitante',
            name='entrada',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='eventovisitante',
            name='salida',
            field=models.BooleanField(default=0),
        ),
    ]
