# Generated by Django 5.1 on 2025-02-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_eventovisitante_entrada_eventovisitante_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventovisitante',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventovisitante',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
