# Generated by Django 5.1 on 2025-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_eventocapacitacion_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocapacitacion',
            name='estado',
            field=models.CharField(default='activo', max_length=255),
        ),
    ]
