# Generated by Django 5.1 on 2025-02-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PertenenciasVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_visitante', models.CharField(max_length=50)),
                ('pertenencias_entrada', models.TextField()),
                ('pertenencias_salida', models.TextField(blank=True, null=True)),
                ('observaciones_ingreso', models.TextField(blank=True, null=True)),
                ('observaciones_salida', models.TextField(blank=True, null=True)),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('usuario_registro_ingreso', models.CharField(max_length=50)),
                ('usuario_registro_salida', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
