# Generated by Django 5.1 on 2025-02-20 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_visitante_cod_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='cod_visita',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
