# Generated by Django 5.1 on 2025-02-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_visita_cod_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='num_pase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
