# Generated by Django 5.1 on 2025-02-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_visita_num_pase'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivovisita',
            name='accion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
