# Generated by Django 5.1 on 2025-02-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0006_areadepto_colaborador_alter_visitante_cod_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='agendado_presente',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='estado_visitante',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
