# Generated by Django 5.1 on 2025-02-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0007_visita_agendado_presente_visita_estado_visitante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acompanante',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='foto_documento_identificacion',
        ),
        migrations.AddField(
            model_name='visita',
            name='foto_documento_identificacion',
            field=models.ImageField(blank=True, null=True, upload_to='visitantes/'),
        ),
    ]
