# Generated by Django 5.1 on 2025-02-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0008_delete_acompanante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitanesVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_visita', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('documento_identificacion', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
