# Generated by Django 5.1 on 2025-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0009_visitanesvisita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitanesvisita',
            name='documento_identificacion',
            field=models.CharField(max_length=50),
        ),
    ]
