# Generated by Django 5.1 on 2025-02-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0010_alter_visitanesvisita_documento_identificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
