# Generated by Django 5.1 on 2025-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0011_accionvisita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='accion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
