# Generated by Django 5.1 on 2025-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0012_visita_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='documento_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
