# Generated by Django 5.1 on 2025-04-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioReloj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('privilegio', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=50)),
                ('grupo', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_evento', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biometrico.usuarioreloj', to_field='user_id')),
            ],
        ),
    ]
