# Generated by Django 5.1 on 2025-04-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarioreloj',
            name='card',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='tipo_evento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioreloj',
            name='grupo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usuarioreloj',
            name='privilegio',
            field=models.IntegerField(default=0),
        ),
    ]
