# Generated by Django 5.1 on 2025-04-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0002_remove_registroasistencia_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioreloj',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
