# Generated by Django 5.1 on 2025-04-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0003_alter_usuarioreloj_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioreloj',
            name='user_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
