# Generated by Django 5.1 on 2025-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0005_colaborador_documentocolaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='metodo_autenticacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
