# Generated by Django 5.1 on 2025-04-07 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0006_registroasistencia_metodo_autenticacion'),
        ('visitantes', '0014_alter_colaborador_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAsistenciaColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('jornada', models.CharField(default='Normal', max_length=20)),
                ('horario', models.CharField(default='08:00 a 17:00', max_length=50)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('razon', models.CharField(blank=True, max_length=255, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('columna_1', models.CharField(blank=True, max_length=255, null=True)),
                ('columna_2', models.CharField(blank=True, max_length=255, null=True)),
                ('columna_3', models.CharField(blank=True, max_length=255, null=True)),
                ('columna_4', models.CharField(blank=True, max_length=255, null=True)),
                ('columna_5', models.CharField(blank=True, max_length=255, null=True)),
                ('total_horas', models.DurationField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitantes.colaborador')),
            ],
            options={
                'unique_together': {('colaborador', 'fecha')},
            },
        ),
    ]
