# Generated by Django 5.1 on 2025-04-07 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0007_reporteasistenciacolaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteasistenciacolaborador',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometrico.colaborador'),
        ),
    ]
