# Generated by Django 5.1 on 2025-04-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0008_alter_reporteasistenciacolaborador_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biometrico.horariolaboral'),
        ),
        migrations.CreateModel(
            name='HorarioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('mon', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miércoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sábado'), ('sun', 'Domingo')], max_length=3)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='biometrico.horariolaboral')),
            ],
            options={
                'ordering': ['horario', 'dia'],
                'unique_together': {('horario', 'dia')},
            },
        ),
    ]
