# Generated by Django 5.1 on 2025-04-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0009_horariolaboral_colaborador_horario_horariodia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometrico.colaborador')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometrico.horariolaboral')),
            ],
            options={
                'ordering': ['colaborador', 'fecha_inicio'],
            },
        ),
    ]
