# Generated by Django 5.1 on 2025-04-09 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_estado', models.CharField(blank=True, max_length=10, null=True)),
                ('ultimo_detalle', models.TextField(blank=True, null=True)),
                ('ultima_revision', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChequeoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chequeos', to='logs.servicioweb')),
            ],
        ),
    ]
