# Generated by Django 5.1 on 2025-03-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paseacceso',
            name='comentario_reporte',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
