# Generated by Django 5.1 on 2025-02-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaNegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identificacion', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('foto_documento_identificacion', models.ImageField(blank=True, null=True, upload_to='lista_negra/')),
                ('motivo', models.TextField()),
                ('usuario_registro', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
